//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRUDoperations.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAIOEntities1 : DbContext
    {
        public DbAIOEntities1()
            : base("name=DbAIOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasicCRUDTblCategory> BasicCRUDTblCategories { get; set; }
        public virtual DbSet<BasicCRUDTblCustomer> BasicCRUDTblCustomers { get; set; }
        public virtual DbSet<BasicCRUDTblProduct> BasicCRUDTblProducts { get; set; }
        public virtual DbSet<BasicCRUDTblSale> BasicCRUDTblSales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
