//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MyPortfolioTblSocialMedia
    {
        [Key]
        public int SocialMediaId { get; set; }

        [Required(ErrorMessage = "Social media name is required.")]
        [StringLength(50, ErrorMessage = "The name cannot exceed 50 characters.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The URL is required.")]
        [Url(ErrorMessage = "Please provide a valid URL.")]
        public string Url { get; set; }
    }
}
