//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAIOEntities1 : DbContext
    {
        public DbAIOEntities1()
            : base("name=DbAIOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyPortfolioTblAbout> MyPortfolioTblAbouts { get; set; }
        public virtual DbSet<MyPortfolioTblBanner> MyPortfolioTblBanners { get; set; }
        public virtual DbSet<MyPortfolioTblCategory> MyPortfolioTblCategories { get; set; }
        public virtual DbSet<MyPortfolioTblContact> MyPortfolioTblContacts { get; set; }
        public virtual DbSet<MyPortfolioTblEducation> MyPortfolioTblEducations { get; set; }
        public virtual DbSet<MyPortfolioTblExperience> MyPortfolioTblExperiences { get; set; }
        public virtual DbSet<MyPortfolioTblExpertis> MyPortfolioTblExpertises { get; set; }
        public virtual DbSet<MyPortfolioTblMessage> MyPortfolioTblMessages { get; set; }
        public virtual DbSet<MyPortfolioTblProject> MyPortfolioTblProjects { get; set; }
        public virtual DbSet<MyPortfolioTblSocialMedia> MyPortfolioTblSocialMedias { get; set; }
        public virtual DbSet<MyPortfolioTblTestimonial> MyPortfolioTblTestimonials { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
    }
}
