//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MyPortfolioTblBanner
    {
        [Key]
        public int BannerId { get; set; }
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(25, ErrorMessage = "Title cannot exceed 25 characters.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description address is required.")]
        [StringLength(150,ErrorMessage = "Description cannot exceed 150 characters.")]
        public string Description { get; set; }
    }
}
