//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class MyPortfolioTblTestimonial
    {
        [Key]
        public int TestimonialId { get; set; }
        [Required(ErrorMessage = "Name and surname are required.")]
        [StringLength(50, ErrorMessage = "Name and surname must not exceed 50 characters.")]
        public string NameSurname { get; set; }

        [Required(ErrorMessage = "Title cannot be empty. Please provide a title.")]
        [StringLength(50, ErrorMessage = "Title must not exceed 50 characters.")]
        public string Title { get; set; }

        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Comment cannot be empty. Please provide your feedback.")]
        [StringLength(250, ErrorMessage = "Comments must not exceed 250 characters.")]
        public string Comment { get; set; }
        [NotMapped]
        public HttpPostedFileBase TestimonialImage { get; set; }
    }
}
