//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MyPortfolioTblEducation
    {
        [Key]
        public int EducationId { get; set; }

        [Required(ErrorMessage = "School name is required.")]
        [StringLength(100, ErrorMessage = "School name cannot exceed 100 characters.")]
        public string SchoolName { get; set; }

        [Required(ErrorMessage = "Department name is required.")]
        [StringLength(40, ErrorMessage = "Department name cannot exceed 40 characters.")]
        public string Department { get; set; }

        [Required(ErrorMessage = "Start date is required.")]
        [DataType(DataType.Date, ErrorMessage = "Start date must be a valid date.")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date, ErrorMessage = "End date must be a valid date.")]
        public DateTime? EndDate { get; set; }

        [StringLength(100, ErrorMessage = "Description cannot exceed 100 characters.")]
        public string Description { get; set; }
    }
}
