//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MyPortfolioTblContact
    {
        [Key]
        public int ContactId { get; set; }

        [Required(ErrorMessage = "Phone number is required.")]
        [StringLength(20, ErrorMessage = "Phone number cannot exceed 20 characters.")]
        [Phone(ErrorMessage = "Please provide a valid phone number.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [StringLength(50, ErrorMessage = "Email address cannot exceed 50 characters.")]
        [EmailAddress(ErrorMessage = "Please provide a valid email address.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        [StringLength(20, ErrorMessage = "Title cannot exceed 20 characters.")]
        public string Title { get; set; }
        
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(150, ErrorMessage = "Description cannot exceed 150 characters.")]
        public string Description { get; set; }
    }
}
