//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class MyPortfolioTblMeta
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Page title is required.")]
        [StringLength(50, ErrorMessage = "Page title cannot exceed 50 characters.")]
        public string PageTitle { get; set; }
        [Required(ErrorMessage = "Page description is required.")]
        [StringLength(160, ErrorMessage = "Page description cannot exceed 160 characters.")]
        public string PageDescription { get; set; }
        [Required(ErrorMessage = "Page OG image URL is required.")]
        [StringLength(200, ErrorMessage = "Page OG image URL cannot exceed 200 characters.")]
        public string PageOgImage { get; set; }
        [NotMapped]
        public HttpPostedFileBase ogImage { get; set; }
    }
}
