//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class MyPortfolioTblAbout
    {
        [Key]
        public int AboutId { get; set; }
        [Required(ErrorMessage = "Image URL is required.")]
        public string ImageUrl { get; set; }
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(50, ErrorMessage = "Title cannot exceed 50 characters.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Description is required.")]
        [StringLength(500, ErrorMessage = "Description cannot exceed 500 characters.")]
        public string Description { get; set; }
        [Required(ErrorMessage = "CvUrl is required.")]
        public string CvUrl { get; set; }
        [NotMapped]
        public HttpPostedFileBase AboutImage { get; set; }
        [NotMapped]
        public HttpPostedFileBase AboutCV { get; set; }
    }
}
